version: "3"


networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.10.0/24

services:
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: "mysql"
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
     - ${PMA_LOCAL_PORT}:80
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      frontend:
        ipv4_address: 172.20.10.2
  mailhog:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    image: mailhog/mailhog
    networks:
      frontend:
        ipv4_address: 172.20.10.3
    ports:
      - ${MAILHOG_LOCAL_PORT}:8025
  apache:
    labels:
      - 'traefik.docker.network=frontend'
      - 'traefik.backend=${COMPOSE_PROJECT_NAME}_apache'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}, bh.${PROJECT_BASE_URL}'
    networks:
      frontend:
        ipv4_address: 172.20.10.4
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    build:
      context: ./docker/apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    volumes:
      - ./:${PHP_APP_DIR}
      - ./logs/apache:${APACHE_ROOT_DIR}/logs
    ports:
      - ${APACHE_LOCAL_PORT}:80
      - 8085:80
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
      - PHP_DOCROOT=${PHP_DOCROOT}
      - PHP_APP_DIR=${PHP_APP_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
  mysql:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      frontend:
        ipv4_address: 172.20.10.5
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    build:
      context: ./docker/mysql
      args:
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
    volumes:
      - ./logs/mysql:${MYSQL_LOG_DIR}
      - dbvolume:${MYSQL_DATA_DIR}
    environment:
      - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  php:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      frontend:
        ipv4_address: 172.20.10.6
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./docker/php
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
    working_dir: ${PHP_APP_DIR}/docroot
    volumes:
      - ./:${PHP_APP_DIR}
      - ./logs/php:${PHP_ROOT_DIR}/logs
    depends_on:
      - apache
      - mysql
    environment:
      - PHP_DOCROOT=${PHP_DOCROOT}
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  traefik:
    image: traefik
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '83:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      frontend:
        ipv4_address: 172.20.10.7
    dns:
    - 8.8.8.8
    - 8.8.4.4

volumes:
  dbvolume:
